POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "VS code rest client is a handy tool",
  "author": "Minna",
  "url": "https://marketplace.visualstudio.com/items?itemName=humao.rest-client",
  "likes": 5
}